import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import DrawerAppBar from "./components/Navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <DrawerAppBar/>

      <div className="mt-16">{children}</div>
        </body>
    </html>
  );
}
